default_agent: ac_orchestration_agent
agents:
  ac_orchestration_agent:
    name: ac_orchestration_agent
    entrypoint: /Users/shaoyili/disagree-and-commit/workshops/agent-core/orchestration_agent/orchestration_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::383661100299:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-2bf471acce
      execution_role_auto_create: false
      account: '383661100299'
      region: us-east-1
      ecr_repository: 383661100299.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ac_orchestration_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ac_orchestration_agent-m90OilFV5f
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:383661100299:runtime/ac_orchestration_agent-m90OilFV5f
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ac_orchestration_agent-builder
      execution_role: arn:aws:iam::383661100299:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2bf471acce
      source_bucket: bedrock-agentcore-codebuild-sources-383661100299-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
